### ISSUE TITLE
True source for the custom code

### ISSUE THREAD

**Issue by andybak** [landonth/unity-vfx-custom-addons#1]
As lovely as it is to receive a credit I don't think I deserve this one. 

I think you probably got the custom code functionality from: https://github.com/IxxyXR/Parametric-VFX

and then simplified it to remove all the preset formula stuff. If so - I basically got the custom code feature from @peeweek: https://github.com/peeweek/net.peeweek.vfxgraph-extras/tree/master/Editor/Blocks/CustomCode

and added in the stuff you later removed! So you've basically just returned it to the state I found it in ;-)

Which reminds me. I should probably credit my source in the readme there. I always intended to do more with that project but I got sidelined.

**Comment by loopervfx** [comment]
oh hey there. no harm, no foul! I have heard of @peeweek of course but i haven't seen his github repos. i appreciate the background on this and i will add a credit for the custom code block.
