### ISSUE TITLE
Creating and assigning the structured buffer

### ISSUE THREAD

**Issue by BarakChamo** [landonth/unity-vfx-custom-addons#2]
Hi @landonth !

Thanks for this excellent reference on how to get VFX output on to a buffer.

Would you be able to provide a brief reference for correctly creating, assigning and accessing the computer buffer used in the output? I understand this is a global buffer but it seems to never be created by the OutputBuffer script, would the structured buffer in an related shader need to match the same structure and order as in the VFX Graph?

Would appreciate any pointers!

**Comment by loopervfx** [comment]
@BarakChamo Yes the structured buffer in a related shader needs to match the same structure and order as in the Output shader generated by VFX Graph the only catch is the bool alive attribute must be duplicated as uint _alive because the type must be blittable (booleans aren't blittable.) I don't have time to put together a reference doc or example project right now, though I likely will sometime next year. Or if anyone wants to contribute either of these, I'm happy to add you as a contributor.

A separate issue is that it's not working with HDRP currently, tracked in issue #3 which will also need to be resolved first as that is the primary render pipeline supported by VFX graph right now (URP support is only in preview, and BRP sorta works but it is entirely unsupported by Unity.)

**Comment by BarakChamo** [comment]
@landonth thanks for that, I'm happy to dig on my own to try and get that to work and share if it amounts to anything.

Can I just ask for a quick pointer?
The `VFXBufferOutput.cs` portion that constructs the ShaderWriter doesn't seem to follow the order of values packed in the Graph's inspector.

```csharp
  var bufferStoreAttributes = new VFXShaderWriter();
  bufferStoreAttributes.WriteLine($"{bufferName}[index].position = attributes.position;");
  bufferStoreAttributes.WriteLine($"{bufferName}[index].velocity = attributes.velocity;");
  bufferStoreAttributes.WriteLine($"{bufferName}[index].color = attributes.color;");
  bufferStoreAttributes.WriteLine($"{bufferName}[index].alpha = attributes.alpha;");
  bufferStoreAttributes.WriteLine($"{bufferName}[index].size = attributes.size;");
  bufferStoreAttributes.WriteLine($"{bufferName}[index]._alive = attributes.age + 0.1 > attributes.lifetime ? false : true;");
```

vs.

![image](https://user-images.githubusercontent.com/2883345/103242975-36afae00-4926-11eb-82f8-d86428b044ed.png)

Am I understanding correctly that these `.WriteLine()` calls add to the constructed output shader? 
Are the attributes written to the computer buffer in that order? or is the struct otherwise defined?

Following that bit of code I tried the following struct that doesn't seem to work:
```hlsl
struct VFXOutput {
	float3 position;
	float3 velocity;
	float3 color;
	float alpha;
	float3 size;
	float _alive;
};
```

Appreciate you're probably busy, just a quick pointer to the correct struct form would be great!

**Comment by BarakChamo** [comment]
Couldn't really get this to work but I imagine the issue you mentioned has something to do with it.
No errors, just seems like data is not actually being written to the texture.

For the record, I created it like this:
```csharp
// Define VFX output target buffer
VFXOutputTarget = new ComputeBuffer(capacity, stride, ComputeBufferType.IndirectArguments & ComputeBufferType.Structured);
Graphics.SetRandomWriteTarget(register, VFXOutputTarget,true);
Shader.SetGlobalBuffer("VFXOutputBuffer", VFXOutputTarget);
```

where `register` was also set in the output inside the Graph editor and the struct matched the attribute layout on the Output node:
```hlsl
struct VFXOutput {
	float3 velocity;
	float lifetime;
	float3 position;
	bool alive;
	float age;
	float _alive;
};
```

Happy to poke further if I know where.

**Comment by loopervfx** [comment]
@BarakChamo FYI i've got a fix for HDRP coming soon as noted in issue  #3 . I'm busy rn but remind me in a month , i will have some time then to get this updated.
